micronaut:
  application:
    name: template-apis
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

  server:
    #    host: 192.168.2.39
    port: 8081
    cors:
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

datasources:
  default:
    url: "jdbc:postgresql://${DB_HOST:`localhost`}/${DB_NAME:`test2`}"
    username: "${DB_USER:`logineo`}"
    password: "${DB_PASSWORD:`logineopg`}"
    driverClassName: 'org.postgresql.Driver'
    maxLifetime: 3600000 #60 minutes
    maximumPoolSize: 20
    minimumIdle: 5


jpa:
  default:
    entity-scan:
#      classpath: true
      packages:
        - 'com.logineo.core'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
      show_sql: true

netty:
  default:
    allocator:
      max-order: 3
